src/Entity/Company.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Table(name="tbl_company")
 * @ORM\Entity(repositoryClass="App\Repository\CompanyRepository")
 */
class Company
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $corporate_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $reference_number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone_number;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Trainee", mappedBy="company", orphanRemoval=true)
     */
    private $trainees;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $street;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    public function __construct()
    {
        $this->trainees = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->corporate_name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCorporateName(): ?string
    {
        return $this->corporate_name;
    }

    public function setCorporateName(string $corporate_name): self
    {
        $this->corporate_name = $corporate_name;

        return $this;
    }

    public function getReferenceNumber(): ?string
    {
        return $this->reference_number;
    }

    public function setReferenceNumber(?string $reference_number): self
    {
        $this->reference_number = $reference_number;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    /**
     * @return Collection|Trainee[]
     */
    public function getTrainees(): Collection
    {
        return $this->trainees;
    }

    public function addTrainee(Trainee $trainee): self
    {
        if (!$this->trainees->contains($trainee)) {
            $this->trainees[] = $trainee;
            $trainee->setCompany($this);
        }

        return $this;
    }

    public function removeTrainee(Trainee $trainee): self
    {
        if ($this->trainees->contains($trainee)) {
            $this->trainees->removeElement($trainee);
            // set the owning side to null (unless already changed)
            if ($trainee->getCompany() === $this) {
                $trainee->setCompany(null);
            }
        }

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(?string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(?string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }
}

src/Entity/Session.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="tbl_session")
 * @ORM\Entity(repositoryClass="App\Repository\SessionRepository")
 */
class Session
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $comment;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Training", inversedBy="sessions")
     * @ORM\JoinColumn(nullable=true)
     */
    private $training;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Location", inversedBy="sessions")
     * @ORM\JoinColumn(nullable=true)
     */
    private $location;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Instructor", inversedBy="sessions")
     * @ORM\JoinColumn(nullable=true)
     */
    private $instructors;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Trainee", inversedBy="sessions")
     */
    private $trainees;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Upload", inversedBy="sessions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $upload;

    /**
     * @ORM\Column(type="time")
     */
    private $start_time_am;

    /**
     * @ORM\Column(type="time")
     */
    private $end_time_am;

    /**
     * @ORM\Column(type="time")
     */
    private $start_time_pm;

    /**
     * @ORM\Column(type="time")
     */
    private $end_time_pm;


    public function __construct()
    {
        $this->instructors = new ArrayCollection();
        $this->trainees = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getTraining()->getTitle();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getTraining(): ?Training
    {
        return $this->training;
    }

    public function setTraining(?Training $training): self
    {
        $this->training = $training;

        return $this;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): self
    {
        $this->location = $location;

        return $this;
    }

    /**
     * @return Collection|Instructor[]
     */
    public function getInstructors(): Collection
    {
        return $this->instructors;
    }

    public function addInstructor(Instructor $instructor): self
    {
        if (!$this->instructors->contains($instructor)) {
            $this->instructors[] = $instructor;
        }

        return $this;
    }

    public function removeInstructor(Instructor $instructor): self
    {
        if ($this->instructors->contains($instructor)) {
            $this->instructors->removeElement($instructor);
        }

        return $this;
    }

    /**
     * @return Collection|Trainee[]
     */
    public function getTrainees(): Collection
    {
        return $this->trainees;
    }

    public function addTrainee(Trainee $trainee): self
    {
        if (!$this->trainees->contains($trainee)) {
            $this->trainees[] = $trainee;
        }

        return $this;
    }

    public function removeTrainee(Trainee $trainee): self
    {
        if ($this->trainees->contains($trainee)) {
            $this->trainees->removeElement($trainee);
        }

        return $this;
    }

    public function getUpload(): ?Upload
    {
        return $this->upload;
    }

    public function setUpload(?Upload $upload): self
    {
        $this->upload = $upload;

        return $this;
    }

    public function getStartTimeAm(): ?\DateTimeInterface
    {
        return $this->start_time_am;
    }

    public function setStartTimeAm(\DateTimeInterface $start_time_am): self
    {
        $this->start_time_am = $start_time_am;

        return $this;
    }

    public function getEndTimeAm(): ?\DateTimeInterface
    {
        return $this->end_time_am;
    }

    public function setEndTimeAm(\DateTimeInterface $end_time_am): self
    {
        $this->end_time_am = $end_time_am;

        return $this;
    }

    public function getStartTimePm(): ?\DateTimeInterface
    {
        return $this->start_time_pm;
    }

    public function setStartTimePm(\DateTimeInterface $start_time_pm): self
    {
        $this->start_time_pm = $start_time_pm;

        return $this;
    }

    public function getEndTimePm(): ?\DateTimeInterface
    {
        return $this->end_time_pm;
    }

    public function setEndTimePm(\DateTimeInterface $end_time_pm): self
    {
        $this->end_time_pm = $end_time_pm;

        return $this;
    }
}

src/Entity/Trainee.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="tbl_trainee")
 * @ORM\Entity(repositoryClass="App\Repository\TraineeRepository")
 */
class Trainee
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @ORM\JoinColumn(name="last_name")
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Company", inversedBy="trainees")
     * @ORM\JoinColumn(nullable=false)
     */
    private $company;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Session", mappedBy="trainees")
     */
    private $sessions;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $civility;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->last_name.' '.$this->first_name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }

    /**
     * @return Collection|Session[]
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): self
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions[] = $session;
            $session->addTrainee($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->sessions->contains($session)) {
            $this->sessions->removeElement($session);
            $session->removeTrainee($this);
        }

        return $this;
    }

    public function getCivility(): ?string
    {
        return $this->civility;
    }

    public function setCivility(?string $civility): self
    {
        $this->civility = $civility;

        return $this;
    }
}

src/Entity/Upload.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Form\Extension\Core\Type\FileType;

/**
 * @ORM\Table(name="tbl_upload")
 * @ORM\Entity(repositoryClass="App\Repository\UploadRepository")
 */
class Upload
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $file_name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Session", mappedBy="upload", orphanRemoval=true)
     */
    private $sessions;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFileName()
    {
        return $this->file_name;
    }

    public function setFileName($file_name)
    {
        $this->file_name = $file_name;

        return $this;
    }

    /**
     * @return Collection|Session[]
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): self
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions[] = $session;
            $session->setUpload($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->sessions->contains($session)) {
            $this->sessions->removeElement($session);
            // set the owning side to null (unless already changed)
            if ($session->getUpload() === $this) {
                $session->setUpload(null);
            }
        }

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }
}

src/Form/SessionType.php
<?php

namespace App\Form;

use App\Entity\Session;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class SessionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {   
        $builder
            ->add('training')
            ->add('location', null, [
                'required' => true,
            ])
            ->add('instructors', null, [
                'required' => true,
            ])
            ->add('date', DateType::Class , [
                'widget' => 'single_text',
            ])
            ->add('start_time_am', TimeType::Class , [
                'widget' => 'single_text',
            ])
            ->add('end_time_am', TimeType::Class , [
                'widget' => 'single_text',
            ])
            ->add('start_time_pm', TimeType::Class , [
                'widget' => 'single_text',
            ])
            ->add('end_time_pm', TimeType::Class , [
                'widget' => 'single_text',
            ])
            ->add('comment')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Session::class,
        ]);
    }
}

templates/session/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{'Session index'|trans}}{% endblock %}

{% block body %}

    {% if app.request.get('new') == 'success' %}
        <div class="text-center mx-auto alert alert-success alert-dismissable fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>

            <h5>{{'Training successfuly added'|trans}}</h5>
        </div>
    {% endif %}

    <h1 class='text-center mb-3'>{{'Sessions list'|trans}}</h1>

    <div class='row justify-content-center'>
        <div class='col text-center mb-3'>
            <a href="{{ path('session_export') }}"><button class="btn btn-lg btn-no-bg hover-pr rad-rounded-xs px-5">{{'Export to Excel'|trans}}</button></a>
        </div>
    </div>

    <div class="row text-center tab-header">
        <div class="col-5 tab-cell-header px-2 py-2">
            {{'Training'|trans}}
        </div>
        <div class="col-5 tab-cell-header px-2 py-2">
            {{'Training location'|trans}}
        </div>
        <div class="col-2 tab-cell-header px-2 py-2">
            {{'Date'|trans}}
        </div>
    </div>

    {% set previousSessionUpload = '' %}
    {% set color = 'light-alt' %}
    
    {% for session in sessions | sortByField('upload','desc') %}

        {% set currentSessionUpload = session.upload.fileName %}

        {% if currentSessionUpload != previousSessionUpload %}
            {% if color == 'light' %}
                {% set color = 'light-alt' %}
            {% else %}
                {% set color = 'light' %}
            {% endif %}
        {% endif %}
        
        <a href="{{ path('session_show', {'id': session.id}) }}" class="link-unstyled">
            <div class="row text-center tab-row link-style-disabled tab-row-{{ color }}">
                <div class="col-5 tab-cell px-2 py-2">
                    {{ session.training }}
                </div>
                <div class="col-5 tab-cell px-2 py-2">
                    {{ session.location }}
                </div>
                <div class="col-2 tab-cell px-2 py-2">
                    {{ session.date ? session.date|date('d-m-Y') : '' }}
                </div>
            </div>
        </a>

        {% set previousSessionUpload = currentSessionUpload %}

    {% else %}
        <div class='row justify-content-center mt-2'>
            <div class='col text-center'>
                <div class="alert alert-danger">{{'No entry found'|trans}}</div>
            </div>
        </div>
    {% endfor %}
    
{% endblock %}

templates/session/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{'Session'|trans}}{% endblock %}

{% block body %}

    {% if (app.request.get('errors')) or (app.request.get('location_name')) or (app.request.get('location_pc') or (app.request.get('location_street')) or (app.request.get('location_city'))) %}
        <div class="text-center mx-auto mb-5 alert alert-danger alert-dismissable fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>

            {% for error in app.request.get('errors') %}
                {% if error == 'training_title' %}
                    <h5>{{'Please enter a training title'|trans}}</h5>
                    {{ form_start(training.form) }}

                    <h5>{{'Reference number'|trans}}</h5>
                    {{ form_errors(training.form.reference_number) }}
                    {{ form_widget(training.form.reference_number, {'attr': {'class': 'mb-3'}}) }}

                    <div class='row justify-content-center'>
                        <div class='col text-center'>
                            <button class="btn btn-lg btn-primary rad-rounded-xs px-5">{{ button_label|default('Save'|trans) }}</button>
                        </div>
                    </div>
                    {{ form_end(training.form) }}

                {% endif %}
                {% if error == 'training_ref_number' %}
                    <h5>{{'Please enter a training reference number'|trans}}</h5>
                {% endif %}
                {% if error == 'training_goals' %}
                    <h5>{{'Please enter at least one goal for this training'|trans}}</h5>
                {% endif %}
            {% endfor %}

            {% if app.request.get('location_name') %}
                {% for session_date in app.request.get('location_name') %}
                    <h5>{{'Please enter a location name for this session :'|trans}} {{ session_date }}</h5>
                {% endfor %}
            {% endif %}   

            {% if app.request.get('location_pc') %}
                {% for session_date in app.request.get('location_pc') %}
                    <h5>{{'Please enter a location postal code for this session :'|trans}} {{ session_date }}</h5>
                {% endfor %}
            {% endif %}     

            {% if app.request.get('location_street') %}
                {% for session_date in app.request.get('location_street') %}
                    <h5>{{'Please enter a location street for this session :'|trans}} {{ session_date }}</h5>
                {% endfor %}
            {% endif %}  

            {% if app.request.get('location_city') %}
                {% for session_date in app.request.get('location_city') %}
                    <h5>{{'Please enter a city name for this session :'|trans}} {{ session_date }}</h5>
                {% endfor %}
            {% endif %}   
        </div>
    {% endif %}

    {% if app.request.get('location') == 'success' %}
        <div class="text-center mx-auto alert alert-success alert-dismissable fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>

            <h5>{{'Location successfuly updated'|trans}}</h5>
        </div>
    {% endif %}
    {% if app.request.get('training') == 'success' %}
        <div class="text-center mx-auto alert alert-success alert-dismissable fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>

            <h5>{{'Training successfuly updated'|trans}}</h5>
        </div>
    {% endif %}
    {% if app.request.get('update') == 'success' %}
        <div class="text-center mx-auto alert alert-success alert-dismissable fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>

            <h5>{{'Session successfuly updated'|trans}}</h5>
        </div>
    {% endif %}

    <a href="{{ path('session_index') }}"><i class="fas fa-chevron-left h1 back-btn"></i></a>
    
    <div class='row justify-content-center mb-5'>
        <div class='col text-center'>
            <a href="{{ path('session_edit', {'id': session.id}) }}"><button class="btn btn-lg btn-no-bg hover-pr rad-rounded-xs px-5">{{'Edit'|trans}}</button></a>
        </div>
        {% if session.training.platform != 'Formiris' %}
            <div class='col text-center'>
                <a href="{{ path('session_tally_sheet', {'id': session.id}) }}"><button class="btn btn-lg btn-no-bg hover-pr rad-rounded-xs px-5">{{'Tally sheet'|trans}}</button></a>
            </div>
        {% endif %}
    </div>

    <h1 class="text-center mb-5">{{ session.training }}</h1>

    <div class='d-flex row mb-5 justify-content-around'>
    
        <div class='mb-4'>
            <div class='info-box-header p-3 text-center'><i class="info-box-icon far fa-calendar-alt fa-2x"></i><label class='h4 px-3'>{{'Schedules'|trans}}</label></div>
            <div class='info-box-content px-4 py-3 text-center'>
                <h5 class='mb-3'>Le {{ session.date|date("d/m/Y") }}</h5>
                <hr>
                <h5 class="text-center w-100">{{'AM :'|trans}} {{ session.startTimeAm|date("H\\h\i") }}-{{ session.endTimeAm|date("H\\h\i") }}</h5>
                <h5 class="text-center w-100">{{'PM :'|trans}} {{ session.startTimePm|date("H\\h\i") }}-{{ session.endTimePm|date("H\\h\i") }}</h5>
                <hr>
                <h5>{{ session.endTimeAm|date_minus(session.startTimeAm,session.endTimePm,session.startTimePm) }} {{'of training'|trans}}</h5>
            </div>
        </div>

        <div class='mb-4'>
            <div class='info-box-header p-3 text-center'><i class="info-box-icon fas fa-map-marker-alt fa-2x"></i><label class='h4 px-3'>{{'Location'|trans}}</label></div>
            <div class='info-box-content px-4 py-3 text-center'>
                {% if session.location %}
                    {% if session.location.name == null %}
                        <a href="{{ path('location_edit', {'id': session.location.id, 'source': 'session', 'id_session': session.id}) }}"><h5 class="font-italic text-danger">{{'No location name set for this session'|trans}}</h5></a>
                    {% else %}
                        <h5>{{ session.location.name}}</h5>
                    {% endif %}
                    {% if session.location.street == null %}
                        <a href="{{ path('location_edit', {'id': session.location.id, 'source': 'session', 'id_session': session.id}) }}"><h5 class="font-italic text-danger">{{'No location street set for this session'|trans}}</h5></a>
                    {% else %}
                        <h5>{{ session.location.street}}</h5>
                    {% endif %}
                    <h5>{{ session.location.postalCode}} - {{ session.location.city}}</h5>
                {% else %}
                    <a href="{{ path('session_edit', {'id': session.id}) }}"><h5 class="font-italic text-danger">{{'No location set for this session'|trans}}</h5></a>
                {% endif %}
            </div>
        </div>

        <div class='mb-4'>
            <div class='info-box-header p-3 text-center'><i class="info-box-icon fas fa-user-tie fa-2x"></i><label class='h4 px-3'>{{'Instructor'|trans}}</label></div>
            <div class='info-box-content px-4 py-3 text-center'>
                {% if session.instructors|length > 0 %}
                    {% for instructor in session.instructors %}
                        <a href="{{ path('instructor_show', {'id': instructor.id}) }}"><h5>{{ instructor.lastName }} {{ instructor.firstName }}
                        {% if instructor.profession %}
                            ({{ instructor.profession }})</h5>
                        {% endif %}
                        </h5></a>
                        <hr>
                    {% endfor %}
                {% else %}
                    <a href="{{ path('session_edit', {'id': session.id}) }}"><h5 class="font-italic text-danger">{{'No instructor set for this session'|trans}}</h5></a>
                {% endif %}
            </div>
        </div>

        <div class='mb-4'>
            <div class='info-box-header p-3 text-center'><i class="info-box-icon fas fa-hashtag fa-2x"></i><label class='h4 px-3'>{{'Training reference'|trans}}</label></div>
            <div class='info-box-content px-4 py-3 text-center'>
                {% if session.training.referenceNumber != null %}
                    <a href="{{ path('training_show', {'id': session.training.id}) }}"><h5>{{ session.training.referenceNumber }}</h5></a>
                {% else %}
                    <a href="{{ path('training_edit', {'id': session.training.id, 'source': 'session', 'id_session': session.id}) }}"><h5 class="font-italic text-danger">{{'No training reference set for this training'|trans}}</h5></a>
                {% endif %}
            </div>
        </div>

        <div class='mb-4'>
            <div class='info-box-header p-3 text-center'><i class="info-box-icon fas fa-bullseye fa-2x"></i><label class='h4 px-3'>{{'Training goals'|trans}}</label></div>
            <div class='info-box-content px-4 py-3 text-center'>
                {% if session.training.goals|length > 0 %}
                    {% for goal in session.training.goals %}
                        <a href="{{ path('goal_show', {'id': goal.id}) }}"><h5>{{ goal.title }}</h5></a>
                        <hr>
                    {% endfor %}
                {% else %}
                    <a href="{{ path('training_edit', {'id': session.training.id, 'source': 'session', 'id_session': session.id}) }}"><h5 class="font-italic text-danger">{{'No goal set for this training'|trans}}</h5></a>
                {% endif %}
            </div>
        </div>
    </div>

    <a href="/uploads/{{ session.upload.fileName }}">
        <button class="btn btn-lg btn-no-bg hover-pr rad-rounded-xs px-5 mb-3">{{ session.upload.fileName }} <i class="fas fa-download fa-lg"></i></button>
    </a>
    <a href="{{ path('session_all_documents', {'id': session.id}) }}">
        <button class="btn btn-lg btn-no-bg hover-pr rad-rounded-xs px-5 mb-3">{{'Direct mail'|trans}} <i class="fas fa-file-alt fa-lg"></i></button>
    </a>


    <div class="row text-center tab-header">
        <div class="col-2 tab-cell-header px-2 py-2">
            {{'Civility'|trans}}
        </div>
        <div class="col-2 tab-cell-header px-2 py-2">
            {{'Last name'|trans}}
        </div>
        <div class="col-2 tab-cell-header px-2 py-2">
            {{'First name'|trans}}
        </div>
        <div class="col-3 tab-cell-header px-2 py-2">
            {{'Email'|trans}}
        </div>
        <div class="col-3 tab-cell-header px-2 py-2">
            {{'Company'|trans}}
        </div>
    </div>
    {% for trainee in session.trainees %}
        <div class="row text-center tab-row link-style-disabled">
            <div class="col-2 tab-cell px-2 py-2">
                {{ trainee.civility }}
            </div>
            <div class="col-2 tab-cell px-2 py-2">
                {{ trainee.lastName }}
            </div>
            <div class="col-2 tab-cell px-2 py-2">
                {{ trainee.firstName }}
            </div>
            <div class="col-3 tab-cell px-2 py-2">
                {{ trainee.email }}
            </div>
            <div class="col-3 tab-cell px-2 py-2">
                {{ trainee.company.corporateName }}
            </div>
        </div>
    {% else %}
        <div class='row justify-content-center mt-2'>
            <div class='col text-center'>
                <div class="alert alert-danger">{{'No entry found'|trans}}</div>
            </div>
        </div>
    {% endfor %}
    <div class="mb-5"></div>
{% endblock %}