src/Entity/Company.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Table(name="tbl_company")
 * @ORM\Entity(repositoryClass="App\Repository\CompanyRepository")
 */
class Company
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $corporate_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $reference_number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone_number;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Trainee", mappedBy="company", orphanRemoval=true)
     */
    private $trainees;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $street;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    public function __construct()
    {
        $this->trainees = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->corporate_name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCorporateName(): ?string
    {
        return $this->corporate_name;
    }

    public function setCorporateName(string $corporate_name): self
    {
        $this->corporate_name = $corporate_name;

        return $this;
    }

    public function getReferenceNumber(): ?string
    {
        return $this->reference_number;
    }

    public function setReferenceNumber(?string $reference_number): self
    {
        $this->reference_number = $reference_number;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    /**
     * @return Collection|Trainee[]
     */
    public function getTrainees(): Collection
    {
        return $this->trainees;
    }

    public function addTrainee(Trainee $trainee): self
    {
        if (!$this->trainees->contains($trainee)) {
            $this->trainees[] = $trainee;
            $trainee->setCompany($this);
        }

        return $this;
    }

    public function removeTrainee(Trainee $trainee): self
    {
        if ($this->trainees->contains($trainee)) {
            $this->trainees->removeElement($trainee);
            // set the owning side to null (unless already changed)
            if ($trainee->getCompany() === $this) {
                $trainee->setCompany(null);
            }
        }

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(?string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(?string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }
}

src/Entity/Trainee.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="tbl_trainee")
 * @ORM\Entity(repositoryClass="App\Repository\TraineeRepository")
 */
class Trainee
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @ORM\JoinColumn(name="last_name")
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Company", inversedBy="trainees")
     * @ORM\JoinColumn(nullable=false)
     */
    private $company;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Session", mappedBy="trainees")
     */
    private $sessions;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $civility;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->last_name.' '.$this->first_name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }

    /**
     * @return Collection|Session[]
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): self
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions[] = $session;
            $session->addTrainee($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->sessions->contains($session)) {
            $this->sessions->removeElement($session);
            $session->removeTrainee($this);
        }

        return $this;
    }

    public function getCivility(): ?string
    {
        return $this->civility;
    }

    public function setCivility(?string $civility): self
    {
        $this->civility = $civility;

        return $this;
    }
}

src/Form/CompanyType.php
<?php

namespace App\Form;

use App\Entity\Company;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CompanyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('corporate_name')
            ->add('street', null, [
                'required' => true,
            ])
            ->add('postal_code', null, [
                'required' => true,
            ])
            ->add('city', null, [
                'required' => true,
            ])
            ->add('reference_number', null, [
                'required' => true,
            ])
            ->add('phone_number')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Company::class,
        ]);
    }
}

src/Controller/CompanyController.php
<?php

namespace App\Controller;

use App\Entity\Company;
use App\Form\CompanyType;
use App\Repository\CompanyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/company")
 */
class CompanyController extends AbstractController
{
    /**
     * @Route("/", name="company_index", methods={"GET"})
     */
    public function index(CompanyRepository $companyRepository): Response
    {
        return $this->render('company/index.html.twig', [
            'companies' => $companyRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{id}", name="company_show", methods={"GET"})
     */
    public function show(Company $company): Response
    {
        return $this->render('company/show.html.twig', [
            'company' => $company,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="company_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Company $company): Response
    {
        $form = $this->createForm(CompanyType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('company_show', [
                'id' => $company->getId(),
                'update' => 'success'
            ]);
        }

        return $this->render('company/edit.html.twig', [
            'company' => $company,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="company_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Company $company): Response
    {
        if ($this->isCsrfTokenValid('delete'.$company->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($company);
            $entityManager->flush();
        }

        return $this->redirectToRoute('company_index');
    }

}

templates/company/_delete_form.html.twig
<form method="post" action="{{ path('company_delete', {'id': company.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ company.id) }}">
    <div class='row justify-content-center'>
        <div class='col text-center'>
            <button class="btn btn-lg hover-del btn-no-bg rad-rounded-xs px-5">{{'Delete'|trans}}</button>
        </div>
    </div>
</form>

templates/company/_form.html.twig
{{ form_start(form) }}
    <h5>{{'Corporate name'|trans}}</h5>
    {{ form_errors(form.corporate_name) }}
    {{ form_widget(form.corporate_name, {'attr': {'class': 'mb-3'}}) }}

    <h5>{{'Street'|trans}}</h5>
    {{ form_errors(form.street) }}
    {{ form_widget(form.street, {'attr': {'class': 'mb-3'}}) }}

    <h5>{{'Postal code'|trans}}</h5>
    {{ form_errors(form.postal_code) }}
    {{ form_widget(form.postal_code, {'attr': {'class': 'mb-3'}}) }}

    <h5>{{'City'|trans}}</h5>
    {{ form_errors(form.city) }}
    {{ form_widget(form.city, {'attr': {'class': 'mb-3'}}) }}

    <h5>{{'Reference number'|trans}}</h5>
    {{ form_errors(form.reference_number) }}
    {{ form_widget(form.reference_number, {'attr': {'class': 'mb-3'}}) }}

    <h5>{{'Phone'|trans}}</h5>
    {{ form_errors(form.phone_number) }}
    {{ form_widget(form.phone_number, {'attr': {'class': 'mb-5'}}) }}

    <div class='row justify-content-center'>
        <div class='col text-center'>
            <button class="btn btn-lg btn-primary rad-rounded-xs px-5">{{ button_label|default('Save'|trans) }}</button>
        </div>
    </div>
{{ form_end(form) }}

templates/company/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{'Edit Company'|trans}}{% endblock %}

{% block body %}
    <a href="{{ path('company_show', {'id': company.id}) }}"><i class="fas fa-chevron-left h1 back-btn"></i></a>

    <h1 class='text-center mb-5'>{{'Edit Company'|trans}}</h1>

    {{ include('company/_form.html.twig', {'button_label': 'Update'|trans}) }}

    {{ include('company/_delete_form.html.twig') }}
{% endblock %}

templates/company/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{'Company index'|trans}}{% endblock %}

{% block body %}

    <h1 class='text-center mb-3'>{{'Company list'|trans}}</h1>

    <div class="row text-center tab-header">
        <div class="col-4 tab-cell-header px-2 py-2">
            {{'Corporate name'|trans}}
        </div>
        <div class="col-3 tab-cell-header px-2 py-2">
            {{'Street'|trans}}
        </div>
        <div class="col-2 tab-cell-header px-2 py-2">
            {{'Postal code'|trans}}
        </div>
        <div class="col-3 tab-cell-header px-2 py-2">
            {{'City'|trans}}
        </div>
    </div>
    {% for company in companies | sortByField('corporateName','asc') %}
        <a href="{{ path('company_show', {'id': company.id}) }}" class="link-unstyled">
            <div class="row text-center tab-row link-style-disabled">
                <div class="col-4 tab-cell px-2 py-2">
                    {{ company.corporateName }}
                </div>
                <div class="col-3 tab-cell px-2 py-2">
                    {{ company.street }}
                </div>
                <div class="col-2 tab-cell px-2 py-2">
                    {{ company.postalCode }}
                </div>
                <div class="col-3 tab-cell px-2 py-2">
                    {{ company.city }}
                </div>
            </div>
        </a>
    {% else %}
        <div class='row justify-content-center mt-2'>
            <div class='col text-center'>
                <div class="alert alert-danger">{{'No entry found'|trans}}</div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

templates/company/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{'Company'|trans}}{% endblock %}

{% block body %}

    {% if app.request.get('update') == 'success' %}
        <div class="text-center mx-auto alert alert-success alert-dismissable fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>

            <h5>{{'Company successfuly updated'|trans}}</h5>
        </div>
    {% endif %}

    <a href="{{ path('company_index') }}"><i class="fas fa-chevron-left h1 back-btn"></i></a>
    
    <div class='row justify-content-center mb-5'>
        <div class='col text-center'>
            <a href="{{ path('company_edit', {'id': company.id}) }}"><button class="btn btn-lg btn-no-bg hover-pr rad-rounded-xs px-5">{{'Edit'|trans}}</button></a>
        </div>
    </div>

    <h1 class="text-center mb-5">{{ company.corporateName }}</h1>

    <div class='d-flex row mb-5 justify-content-around'>
    
        <div class='mb-4'>
            <div class='info-box-header p-3 text-center'><i class="info-box-icon fas fa-map-marker-alt fa-2x"></i><label class='h4 px-3'>{{'Address'|trans}}</label></div>
            <div class='info-box-content px-4 py-3 text-center'>
                {% if (company.street) and (company.city) %}
                    <h5>{{ company.street }}</h5>
                    <h5>{{ company.postalCode }} - {{ company.city }}</h5>
                {% else %}
                    <a href="{{ path('company_edit', {'id': company.id}) }}"><h5 class="font-italic text-danger">{{'No address set for this company'|trans}}</h5></a>
                {% endif %}
            </div>
        </div>

        <div class='mb-4'>
            <div class='info-box-header p-3 text-center'><i class="info-box-icon fas fa-phone fa-2x"></i><label class='h4 px-3'>{{'Phone'|trans}}</label></div>
            <div class='info-box-content px-4 py-3 text-center'>
                {% if (company.phoneNumber ) %}
                    <h5>0{{ company.phoneNumber }}</h5>
                {% else %}
                    <a href="{{ path('company_edit', {'id': company.id}) }}"><h5 class="font-italic text-danger">{{'No phone number set for this company'|trans}}</h5></a>
                {% endif %}
            </div>
        </div>

        <div class='mb-4'>
            <div class='info-box-header p-3 text-center'><i class="info-box-icon fas fa-hashtag fa-2x"></i><label class='h4 px-3'>{{'Reference number'|trans}}</label></div>
            <div class='info-box-content px-4 py-3 text-center'>
                {% if (company.referenceNumber) %}
                    <h5>{{ company.referenceNumber }}</h5>
                {% else %}
                    <a href="{{ path('company_edit', {'id': company.id}) }}"><h5 class="font-italic text-danger">{{'No reference number set for this company'|trans}}</h5></a>
                {% endif %}
            </div>
        </div>

        <div class='mb-4'>
            <div class='info-box-header p-3 text-center'><i class="info-box-icon fas fa-user-tie fa-2x"></i><label class='h4 px-3'>{{'Associated trainees'|trans}}</label></div>
            <div class='info-box-content px-4 py-3 text-center'>
                {% if company.trainees|length > 0 %}
                    {% for trainee in company.trainees %}
                        <a href="{{ path('trainee_show', {'id': trainee.id}) }}"><h5>{{ trainee.lastName }} {{ trainee.firstName }}</h5></a>
                        <hr>
                    {% endfor %}
                {% else %}
                    <h5 class="font-italic text-danger">{{'No trainees set for this company'|trans}}</h5>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}